# Generated by Django 3.0.3 on 2020-08-08 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_programmanager_school_student_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='teacher',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='subject',
            new_name='testtype',
        ),
        migrations.DeleteModel(
            name='ProgramManager',
        ),
        migrations.DeleteModel(
            name='School',
        ),
    ]
