# Generated by Django 3.0.3 on 2020-08-08 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_course_video_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='video_link',
            field=models.CharField(max_length=100),
        ),
    ]
