# Generated by Django 3.0.3 on 2020-08-08 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200809_0240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='video_link',
        ),
    ]
