# Generated by Django 3.0.6 on 2020-08-08 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.CharField(max_length=100, unique=True)),
                ('book_name', models.CharField(max_length=100)),
                ('author_name', models.CharField(max_length=100)),
                ('about', models.CharField(max_length=250)),
                ('doa', models.DateField()),
                ('employee', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
